site:
  name: Web Fragments
  site: "https://github.com/web-fragments/web-fragments"
  base: "/"
  trailingSlash: false

  googleSiteVerificationId: ""

# Default SEO metadata
metadata:
  title:
    default: Web Fragments
    template: "%s â€” AstroWind"
  description: "\U0001F680 An incremental, low-risk, high ROI approach, to building micro-frontends."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Web Fragments
    images:
      - url: "~/assets/images/wf_cubes_clean_1024_72.webp"
        width: 1200
        height: 628
    type: website
  twitter:
    handle: "@igorminar"
    site: "igor.dev"
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: "system" # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
