#:schema node_modules/wrangler/config-schema.json
name = "pierced-react"
main = "src/worker.ts"
compatibility_date = "2024-06-14"
compatibility_flags = ["nodejs_compat"]

assets = { directory = "dist", binding = "ASSETS" }

[vars]
DEV_MODE = "false"

[env.dev.vars]
DEV_MODE = "true"
