#:schema node_modules/wrangler/config-schema.json
name = "pierced-react"
main = "src/worker.ts"
compatibility_date = "2024-06-14"

assets = { directory = "dist", binding = "ASSETS" }

[vars]
DEV_MODE = "false"

[build]
command = "pnpm --filter pierced-react build"
