name = "pierced-react-qwik"
main = "dist/_worker.js"
compatibility_date = "2024-06-14"
compatibility_flags = ["nodejs_compat", "nodejs_als"]
assets = { directory = "dist", binding = "ASSETS" }

[vars]
DEV_MODE = "false"
